[package]
name = "psoc"
version = "0.1.0"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
edition = "2018"

[dependencies]
purescript-corefn = "0.3.0"
escodegen = "0.4.3"
glob = "0.2.11"
structopt = "0.2.14"
